openapi: 3.0.4
info:
  title: By Trail API
  description: |-
    This is 'By Trail', a SaaS to plan and monitor trekking based 
    on the OpenAPI 3.0 specification.

    Useful links:
    - [The By Trail repository](https://github.com/g-mainardi/by-trail)
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local Docker Server

tags:
  - name: Authentication
    description: User authentication and authorization
  - name: Alerts
    description: Management of user alerts and notifications
  - name: Admin
    description: Administrative operations and management
  - name: Users
    description: User profiles, settings, and lists
  - name: Bivacchi
    description: Management of shelters and bivouacs
  - name: Trails
    description: Management of hiking trails
  - name: Reservations
    description: Bivouac booking management

paths:
  # Authentication
  /login:
    $ref: "./endpoints/authentication.yaml#/~1login"
  /signup:
    $ref: "./endpoints/authentication.yaml#/~1signup"
  # Users
  /users:
    $ref: "./endpoints/users.yaml#/~1users"
  # Bivacchi

  # Trails

  # Reservations

  # Alerts

  # Admin

components:
  schemas:
    User:
      $ref: "./components/schemas/User.yaml"
